{% set name = "medspacy_quickumls" %}
{% set version = "3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/medspacy_quickumls-{{ version }}.tar.gz
  sha256: 09edeb61467f3570e370337c9bb635f65a03246c9c8fd2af0bb9710e75a46a06

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy >=1.8.2
    - spacy >=3.1.3
    - unidecode >=0.4.19
    - nltk >=3.3
    - pysimstring
    - unqlite >=0.8.1
    - pytest >=6
    - six

test:
  imports:
    - quickumls
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Georgetown-IR-Lab/QuickUMLS
  summary: QuickUMLS is a tool for fast, unsupervised biomedical concept extraction from medical text
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - skupr-anaconda
